---
- name: "1Password | Install Application"
  community.general.homebrew:
    name: 1password
    state: latest

- name: "1Password | Login to 1Password"
  community.general.pause:
    prompt: "Please login to 1Password and press Enter to continue"

- name: "1Password | Install CLI"
  community.general.homebrew:
    name: 1password-cli
    state: latest

- name: "1Password | Modify Settings"
  community.general.pause:
    prompt: "Please enable CLI Integration and SSH Agent in 1Passowrd. Once done, press Enter to continue"

- name: "1Password | Install Safari Extension"
  community.general.mas:
    id: 1569813296
    name: "1Password for Safari"
    state: latest